<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Codegen.Common\Codegen.Common.csproj" />
    <ProjectReference Include="..\Web.Api.Common\Web.Api.Common.csproj" />
    <ProjectReference Include="..\Web.Api.Domain\Web.Api.Domain.csproj" />
    <ProjectReference Include="..\Web.Api.Providers\AuthProvider\AuthProvider.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Infrastructure\DI\" />
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
